language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
script:
  - npm run test
  - npm run coverage
after_success:
  - if [ "$TRAVIS_BRANCH" != "master" ]; then npm run report-coverage; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run report-coverage; npm run semantic-relase; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
